import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
        alignItems:'center',
        justifyContent:'center',
        flex:1,
    },
    formContainer:{
        backgroundColor:'#dfdfdfe2',
        width:'90%',
        padding:10,
        gap:10,
        borderRadius:10,
        minHeight:200,
        justifyContent:'center',
    },
    formTitle:{
        fontWeight:'bold',
        textAlign:'center',
        fontSize:30,
        color:'#4e4d4de2',
        padding:10,
    },
    formInscrire:{
        alignSelf:'flex-end',
        color:'#4343d3',
        padding:5,
    }
    ,
    input:{
        padding:5,
        width:'75%',
    },
    formItems:{
        backgroundColor:'#fff',
        borderRadius:20,
        paddingHorizontal:10,
        flexDirection:'row',
        alignItems:'center'
    },
    IconContainer:{
        flexDirection:'row',
        gap:5,
        width:'100%',
        alignItems:'center',
        justifyContent:'center'
    },
    icon:{
        fontSize:30,
        color:'#4e4d4de2'
    },
    socialeLogin:{
        alignItems:'center',
        gap:5,
        backgroundColor:'#dfdfdfe2',
        width:'90%',
        padding:10,
        borderRadius:10,
        marginTop:10,
    },
    socialeLoginTitle:{
        color:'#5d5dc0',
        fontWeight:'500',
    },
    submitContainer:{
        alignItems:'center',
        width:'100%',
    },
    submit:{
        backgroundColor:'blue',
        width:'80%',
    },
    submitText:{
        color:'white'
    }
});